name: Deploy to cPanel via SSH
run-name: Deploy to cPanel by @${{ github.actor }}
on:
  push:
    branches:
      - "main"

jobs:
  web-deploy:
    name: 🚀 Deploy Website Every Commit
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get Latest Code
        uses: actions/checkout@v3

      - name: 📦 Install Packages
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
      - run: npm ci

      - name: 🔨 Build
        run: npm run build

      - name: 📂 Sync Files
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: 198.54.116.208
          remote-user: trenlqan
          ssh-port: 21098
          private-ssh-key: ${{ secrets.SSH_KEY }}
          source-path: ./dist/myr-site/
          destination-path: ~/home/trenlqan/public_html/
